# Metadata
# ---
title: Arctic Bit
description: arctic bit
baseurl: ""
url: "https://wwww.arcticbit.se"
meta:
  logo: /assets/logo-black-white.jpg

# Contact info
# ---
twitter_username: '0x12b'
github_username:  simskij
email: simme@arcticbit.se
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: "articles/*"
    values:
      splash: "/assets/mountains-faded.png"

# Config
# ---
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed