# Metadata
# ---
title: arctic bit
description: arctic bit
baseurl: ""
url: "https://wwww.arcticbit.se"
meta:
  logo: /assets/logo-black-white.jpg

# Contact info
# ---
twitter_username: '0x12b'
github_username:  simskij
email: simme@arcticbit.se

# Config
# ---
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed